# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Catmit < Formula
  desc "AI powered commit message generator"
  homepage "https://github.com/penwyp/catmit"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/penwyp/catmit/releases/download/v0.0.6/catmit_0.0.6_darwin_amd64.tar.gz"
      sha256 "0b6a892b4c7ae9454b24ed37d1d4ae75df8d29ba77407585130596d936f45184"

      def install
        bin.install "catmit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/penwyp/catmit/releases/download/v0.0.6/catmit_0.0.6_darwin_arm64.tar.gz"
      sha256 "6bf8765563ce3dab6b762e9a07cfe24e6a5d6a23053f78e6d69b9616b6a808bf"

      def install
        bin.install "catmit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/penwyp/catmit/releases/download/v0.0.6/catmit_0.0.6_linux_amd64.tar.gz"
      sha256 "ea0b5ce887327909c3cb47d360fef4e789a58edf8e3243789c299cd9652aed15"
      def install
        bin.install "catmit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/penwyp/catmit/releases/download/v0.0.6/catmit_0.0.6_linux_arm64.tar.gz"
      sha256 "96b15fed10be3939e161de4598e157e54439d50705fcb196944fad1379908e2d"
      def install
        bin.install "catmit"
      end
    end
  end

  test do
    system "#{bin}/catmit", "--help"
  end
end
