# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Catmit < Formula
  desc "AI powered commit message generator"
  homepage "https://github.com/penwyp/catmit"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/penwyp/catmit/releases/download/v0.0.8/catmit_0.0.8_darwin_amd64.tar.gz"
      sha256 "5cba7c7a2bd3713d6d3cd9d454405eee35f9234902631eab33dc6d3a02f92b10"

      def install
        bin.install "catmit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/penwyp/catmit/releases/download/v0.0.8/catmit_0.0.8_darwin_arm64.tar.gz"
      sha256 "0a277bd18594f9a609cb22733c065c290541282ef291c587879897650df358ee"

      def install
        bin.install "catmit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/penwyp/catmit/releases/download/v0.0.8/catmit_0.0.8_linux_amd64.tar.gz"
      sha256 "f975b53523dcca9f17107e513d03713e8630a6bcceb6411df3fe81fa14650a9f"
      def install
        bin.install "catmit"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/penwyp/catmit/releases/download/v0.0.8/catmit_0.0.8_linux_arm64.tar.gz"
      sha256 "a418ded2c1526a77d14081bc09f83238743a9acfb8625b2cd3ed83358db0ec14"
      def install
        bin.install "catmit"
      end
    end
  end

  test do
    system "#{bin}/catmit", "--help"
  end
end
